name: Feature Request
description: Suggest a new feature or enhancement for the Chaukas SDK
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in improving the Chaukas SDK! Please provide detailed information about your feature request.

  - type: checkboxes
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature are you requesting?
      options:
        - label: New framework integration (e.g., LangChain, AutoGen)
        - label: Enhancement to existing integration (CrewAI, OpenAI, Google ADK)
        - label: New core SDK functionality
        - label: Configuration/customization options
        - label: Performance improvement
        - label: Developer experience improvement
        - label: Documentation enhancement
        - label: Example/tutorial request
        - label: Other (please specify below)
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What use case does it address?
      placeholder: |
        Currently, when working with [framework/workflow], it's difficult to...
        This makes it hard to achieve...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution in detail
      placeholder: |
        The SDK should provide...
        This would work by...
    validations:
      required: true

  - type: textarea
    id: code-example
    attributes:
      label: Desired API / Code Example
      description: Show how you'd like to use this feature
      render: python
      placeholder: |
        from chaukas.sdk import enable_chaukas

        # Example of how the new feature would be used
        enable_chaukas(
            integrations=["new_framework"],
            new_option=True
        )

  - type: textarea
    id: integration-details
    attributes:
      label: Framework Integration Details (if applicable)
      description: For new framework integrations, provide details
      placeholder: |
        Framework name: LangChain
        Framework version: 0.1.0
        Framework GitHub: https://github.com/...
        Key events to capture:
        - Agent start/end
        - LLM calls
        - Tool usage
        - ...

  - type: dropdown
    id: breaking
    attributes:
      label: Backward Compatibility
      description: Would this change be backward compatible?
      options:
        - "Yes - fully backward compatible"
        - "No - would break existing code"
        - "Unsure"
    validations:
      required: true

  - type: textarea
    id: breaking-details
    attributes:
      label: Breaking Change Details
      description: If this would be a breaking change, explain the impact and migration path
      placeholder: |
        This would break:
        - Existing usage of...
        - Configuration format for...

        Migration path:
        1. Users would need to...
        2. We could provide a migration script that...

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other approaches have you considered? Why is this approach better?
      placeholder: |
        Alternative 1: ...
        - Pros: ...
        - Cons: ...

        Alternative 2: ...
        - Pros: ...
        - Cons: ...

        Preferred approach because...

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your specific use case and how this feature would help
      placeholder: |
        I'm building an agent that...
        This feature would allow me to...
        The benefit would be...
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas (Optional)
      description: Do you have ideas about how this could be implemented?
      placeholder: |
        This could be implemented by:
        1. Adding a new module in src/chaukas/sdk/integrations/...
        2. Extending the BaseIntegration class...
        3. ...

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to contribute this feature?
      options:
        - label: I'd like to work on this feature myself
        - label: I can help test this feature
        - label: I can provide feedback during development

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or references
      placeholder: |
        - Related issues: #123
        - Similar feature in other projects: ...
        - References: ...
